### ISSUE TITLE
Please give credit/do not remove copyright from out/src/embeddedContentDocuments.js

### ISSUE THREAD

**Issue by bmewburn** [DEVSENSE/phptools-docs#14]
This file looks suspiciously like [intelephense's embeddedContentDocuments.js](https://github.com/bmewburn/vscode-intelephense/blob/master/src/embeddedContentDocuments.ts) or a derivative work of. Please reinstate copyright notice and give credit.

**Comment by jakubmisek** [comment]
Hello,

Thank you for letting us know. I have checked the release and it turned out the comment was optimized-out by mistake by the code minifier. It was totally unintended. I'll add the notice explicitly into the README document.
Please let me know if there is anything else we can do and I make sure it will get fixed as soon as possible.
