### ISSUE TITLE
Incorrect error for `@inheritDoc`

### ISSUE THREAD

**Issue by ADmad** [DEVSENSE/phptools-docs#199]
> '@inheritDoc' tag is not defined. Did you mean '{@inheritdoc}'?PHP(PHP6501)

`@inheritdoc` without the curly braces is also a valid docblock tag and support by all major static analysis tools, for e.g. [phpstan](https://github.com/phpstan/phpstan/commit/4e3041164bf23964ab26c85dcc1a07032fb5bfeb). It means to inherit the description and all the tags of the parent class.

**Comment by jakubmisek** [comment]
thank you,

> the original phpstan issue at https://github.com/phpstan/phpstan/issues/1332)

Although, originally @inhertiDoc was used as an **inline** tag, otherwise it does not make much sense. Parent doc block is always inherited if the user does not specify a description, so writing explicitly `/** @inheritdoc */` is redundant.

Nevertheless, we should not nag about it, and just silently allow `@inheritDoc` :)

**Comment by jakubmisek** [comment]
fixed in the next pre-release!

thank you @ADmad
