### ISSUE TITLE
Add `\Exception` to autocompletion list

### ISSUE THREAD

**Issue by d8vjork** [DEVSENSE/phptools-docs#252]
I very often use `\Exception` classes to throw some errors (yeah... I'm lazy enough to write custom exceptions for every error happening)

Just that, will be great to get on the suggestion list (prioritised if possible aka on top of the list), right now isn't:

<img width="897" alt="image" src="https://user-images.githubusercontent.com/2331052/214287474-6e28e3a5-e5c8-4d4c-a26a-0dc525b11593.png">

**Comment by Zerotask** [comment]
As an addition to that, regarding the order of suggestions:
1. classes from the current project
2. standard PHP classes (SPL etc)
3. classes from vendor

So for this use case, if you don't have an Exception class in your project, the standard Exception class should be the first class in the suggestion list.

**Comment by d8vjork** [comment]
Yeah exactly as @Zerotask said, to cover all cases and also be aligned with what I posted here:

https://community.devsense.com/d/648-qol-prioritise-autocompletion-suggestion-result-list

**Comment by jakubmisek** [comment]
Would it make sense to not show some symbols in the completion list? Currently, we're listing basically everything, but I assume some namespaces from vendor may be for internal use only (other languages mark those classes "internal" or "private", or they have an attribute like [EditorHidden] ..)

**Comment by Zerotask** [comment]
Things to consider from my side:
- classes can have an `@deprecated` -> show them in the list with a hint/crossed out
- constructors of classes can be marked as `@internal` -> can be interpreted that the whole class is internal, although I found at least 1 class where we're extending such a class and call the constructor
- there is a class docBlock with `@internal` (https://freek.dev/1370-internal-classes-in-php)

**Comment by jakubmisek** [comment]
@Zerotask good, makes sense. We already handle `@ignore` tag; I'll take a look on the other ones.

So far, I've been able to "force" VSCode to do sorting:

![image](https://user-images.githubusercontent.com/842150/215277485-ab0316bf-9034-4b8e-b3a3-e7b811daf10a.png)

preparing pre-release with some of those improvements

**Comment by jakubmisek** [comment]
@d8vjork @Zerotask would it help to provide a setting for "hidden" namespaces, something like:

```json
"php.completion.ignore": [
  "PHPUnit\\Framework",
  "Internal"
]
```

**Comment by Zerotask** [comment]
It can help, but I don't really want to maintain a list with namespaces. I prefer some logic with automatism which detects specific folders in my working dir and my composer dependencies.
Perhaps an option could be - instead of detecting it by folders - to provide a namespace for src and for tests.
If try to import a class inside a src namespace, it could only show classes from vendor which are normal composer dependencies (not dev deps).
I can summarize my thoughts when I'm at home.

**Comment by jakubmisek** [comment]
@Zerotask If you have anything that would help, I'm sure other users will appreciate it as well.

So far, I'm preparing pre-release which hides `@internal` symbols, and sorts the list by the rules above.

**Comment by jakubmisek** [comment]
pre-release `1.28.12296`:
- `@internal` symbols are not listed in intellisense
- `@deprecated` classes are strikeout
- classes and functions are ordered as described above

**Comment by Zerotask** [comment]
I assume that almost every (serious) PHP project will use composer as it's like a PHP standard and for the autocompletion list you'll need some sort of autoloading.
composer supports PSR-0 and the preferred [PSR-4](https://getcomposer.org/doc/01-basic-usage.md#autoloading). The composer.json schema allows you to define `autoload` and `autoload-dev`.
From this, you can read the namespace and the assigned folder.

Example:
```json
"autoload": {
    "psr-4": {
      "Acme\\MyProduct\\": "src/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "Acme\\MyProductTests\\": "tests/unit/"
    }
  }
```

If you try to import a class, then you could check the namespace of the current class and compare it with the namespaces from composer.json and then you know if it's production or dev and then you load/suggest only the respective classes:
- `autoload` -> `require`
- `autoload-dev` -> `require-dev` + project classes (`autoload`) since you need to import them for testing

**Comment by d8vjork** [comment]
@Zerotask What I think is that these classes needs to be included in the autocomplete list whenever they're triggered within the same folder/path

**Comment by Zerotask** [comment]
> @Zerotask What I think is that these classes needs to be included in the autocomplete list whenever they're triggered within the same folder/path

What exactly do you mean with triggered?

For example: I define PHPUnit as a dev requirement and want to use it only in a test namespace, e. g. Acme\MyProductTests.

If I open a file from src (namespace Acme\MyProduct) and start typing `PHP` I don't want PHPUnit as a suggestion since it's a dev (and not production) requirement

**Comment by d8vjork** [comment]
@Zerotask From the extension perspective, it doesn't know the context you're coding, unless it reads those autoload entries and then base the suggestions on where the path is

What I meant is that namespaces aren't always used, so it should use paths instead to guide those suggestions to the right path, as you said, PHPUnit classes shouldn't be there when writing code from any `autoload` class map, but they need to be there when you're on any of the `autoload-dev`

**Comment by jakubmisek** [comment]
@d8vjork @Zerotask  we can read `composer.json` and remember which namespaces are defined within `"autoload-dev"`; it would give us something like "dev context", and code completion can be adjusted accordingly.

**Comment by Zerotask** [comment]
> unless it reads those autoload entries

that is my suggestion to read it. But I don't know the restrictions/limitations in plugin development. I just say, if it's possible (and I assume that), then it would be the best way regarding developer experience (DX).

> What I meant is that namespaces aren't always used

Yes, that's a point. That's why my suggestion is more of a user story. Besides that, you not only have the namespace, but also the folder (see example above). So that's just a detail if you use namespace or folder for the detection

**Comment by jakubmisek** [comment]
Would it solve the issue I'm having with for example "`Exception`" class/interface? All of them are unnecessary:

![image](https://user-images.githubusercontent.com/842150/215329289-bdbac97f-0166-4bed-bc02-53d4dd5a1b2b.png)

**Comment by d8vjork** [comment]
@jakubmisek yeah, actually its getting messy as it gets all without excluding `*-dev` (`autoload-dev` + `require-dev`)

So this could solve some work on the prioritised autocompletion list (as the one I linked from the forums)

**Comment by Zerotask** [comment]
> An example from Laravel, we've autoload files that doesn't follow `PSR-4` these should then follow the namespaces imported from the same `autoload` paths:

I think the best way is to follow the composer.json specification (https://getcomposer.org/doc/04-schema.md#autoload).
This also covers `"files"`

**Comment by d8vjork** [comment]
@Zerotask Yeah, there are plenty of ways to deal with this autoload, although there are only a few mostly used

**Comment by Zerotask** [comment]
> Would it solve the issue I'm having with for example "`Exception`" class/interface? All of them are unnecessary:
> 
> ![image](https://user-images.githubusercontent.com/842150/215329289-bdbac97f-0166-4bed-bc02-53d4dd5a1b2b.png)

it can be helpful, inside a group, to show classes starting with the typed string before classes which includes the string.

Example:
I start typing `Excep`, then from the vendor folder, first show classes like `Exception` or `ExceptionModel`, followed by classes like `PharException`, since more people will probably start typing from the beginning and not from the middle.

And another thing which is probably already considred:
I have a production requirement called Acme which itself has test classes like AcmeTest. If I start typing `Acme`, it shouldn't suggest the class AcmeTest.

**Comment by jakubmisek** [comment]
> it can be helpful, inside a group, to show classes starting with the typed string before classes which includes the string.

That's completely handled by VSCode itself; I've just moved the non-imported types with long namespace down the list according to the discussion above.

**Comment by jakubmisek** [comment]
I'm closing the issue since I think we fixed the incorrect ordering, missing "Exception" on top of the list, and improved the filtering as much as possible.

We're still open to new suggestions, please start a new discussion for them :)
