### ISSUE TITLE
Version 1.33.12934 Syntax checking is not working

### ISSUE THREAD

**Issue by lexman1958** [DEVSENSE/phptools-docs#320]
After the loading of version 1.33.12934, the syntax checking is not working as before. Example, when i use a variable that does exist, the variable is not highlighted and no error is reported. Additionally, its also allows me to chose the non-existent variable as a super global. See image below:

![PHP Tools Error](https://user-images.githubusercontent.com/127527088/230768348-913a57d1-96d1-42a4-b509-6155be0d797c.png)

**Comment by jakubmisek** [comment]
Thank you for reporting the issue.

Although, we did not change anything related.

Global variables are all treated as if they exist, so this is expected behavior, Only local variables are checked.

Also, I have noticed you have an additional extension for code completion - don't you have everything twice in the code completion? :-)

**Comment by lexman1958** [comment]
@jakubmisek 

Your stated "Global variables are all treated as if they exist, so this is expected behavior, Only local variables are checked."  I am not sure what that means. But all i know is that prior to the update, the variable (irrespective global or local) "requestx" was reporting as undefined but now it is not for global and it says unassigned "unassigned". I am afraid this is unacceptable as i could defining undefined variables everywhere and only know at runtime.

Additionally, i also notice that namespace and calls names are getting underlined. Why is that?

![PHP Tools Error2](https://user-images.githubusercontent.com/127527088/230797921-a77bdce9-fad5-47de-93f0-a66ccd02b7c6.png)

**Comment by lexman1958** [comment]
@jakubmisek 

Thank you so much for the update. Please keep us informed on any progress on the undefined variable. It will help us a heap preventing runtime errors especially in mission critical apps.

**Comment by jakubmisek** [comment]
@lexman1958 thank you, we'll do our best!

**Comment by murugappanrm** [comment]
@jakubmisek 

This is what you said in your previous reply:

"We don't report (and we never reported) undefined global variables by purpose. It gave a lot of false warnings in the user's code. Anyways, I agree it's a useful diagnostic, and I'll add a setting for it.".

I have  2 items that need your advise:

(1) In your reasoning you said that it may give a lot of "false warnings" but after usage for so long it would not and should not. I noticed this when i used PHP Storm IDE. It would highlight the variable as undefined. Contrary to your reasoning, i found i had so much headache in my new project testing where i received so many runtime errors which i could have otherwise avoided and saved time debugging.
(2) When you be adding the setting which alleviate my problems?

**Comment by jakubmisek** [comment]
@murugappanrm I'll be looking into it. For (1) it's difficult to correctly determine undefined global variables in PHP, but we'll figure out something.

The issue above might be caused by VSCode itself when having more than one extension providing the same features.
