### ISSUE TITLE
Add support for generics

### ISSUE THREAD

**Issue by 0x00A1FA** [DEVSENSE/phptools-docs#348]
Hi,

Consider the following code:

![image](https://github.com/DEVSENSE/phptools-docs/assets/110613761/4856297b-3ff8-41be-9c46-adc93fa2cfc7)

Would it be possible to achieve something similar to Vimeo's Psalm static analyzer in the DEVSENSE PHP extension with regards to generics?

This is something that will someday draw me away from PHP if support for generics is not added (at least on a PHPDoc level).

Thanks!

**Comment by jakubmisek** [comment]
@0x00A1FA Hello, and thank you for the suggestion!

We actually recognize the Psalm syntax. However, we don't report such type mismatches because it would cause a lot of false warnings in the user's code (and especially in 3rd party libraries).

Maybe we can add a strictness setting and report it then.
