### ISSUE TITLE
Suggesting nested trait

### ISSUE THREAD

**Issue by vkoori** [DEVSENSE/phptools-docs#350]
The fast code completion feature does not work when using a nested trait. For example, when using Carbon, suggestions for the now method cannot be obtained.

**Comment by jakubmisek** [comment]
I think it's because `now()` is a static method, so the code completion assumes it should be accessed statically through the `::` operator.

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/a43da0d7-4895-48ca-98bf-60c06e6c0de4)

Is it a common practice to access static members with the object instance operator `->`?

**Comment by vkoori** [comment]
I updated the extention version to Pre-Release, and this resolved the issue. Thank you for your assistance. 🙏

**Comment by jakubmisek** [comment]
thank you for the update! I'm glad it works now
