### ISSUE TITLE
Automatic indentation of switch statement is stupid

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#482]
![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/b961e5ba-766b-4a86-b085-58921d2c0a91)

🤦🤦

**Comment by jakubmisek** [comment]
Is it happening after code formatting, or just after pressing `ENTER` key?

We can add automatic formatting (format on type) after typing `:` to solve that.

**Comment by jakubmisek** [comment]
Would it be ok like that?

![vsc-autoformat-case](https://github.com/DEVSENSE/phptools-docs/assets/842150/c096d5b6-18e5-49e2-980e-cc862e005d80)

**Comment by jakubmisek** [comment]
I don't think VSCode supports the "smart indent" feature where we could unindent after `break;` `ENTER`.

I'll release a pre-release soon - it will do the format as shown in the `.gif`.

Do you have enabled `editor.formatOnPaste` and `editor.formatOnType`?

**Comment by php4fan** [comment]
> I don't think VSCode supports the "smart indent" feature where we could unindent after break; ENTER.

That wouldn't cover the cases where there's no break anyway.

> I'll release a pre-release soon - it will do the format as shown in the .gif.

Can't you unindent after `case`+space and `default:`, instead of after `:`??

> Do you have enabled editor.formatOnPaste and editor.formatOnType?

No, neither of them and I'm kind of surprised. Indentation is usually automatically adjusted both as I type and when I paste code, although not always exactly as I would expect. Obviously I would _not_ want the IDE to change stuff back after I have manually changed the formatting to my taste (e.g. in edge cases like splitting long lines into multiple lines, multi-line arrays, multi-line if conditions, etc.).

**Comment by jakubmisek** [comment]
FYI, our code formatter respects relative indentation within multi-lined statements.

**Comment by jakubmisek** [comment]
We can only do it in the scope of "formatOnType" feature, ideally after pressing a character that is not typed so often. Doing it after pressing `:` is ideal. Also, it behaves the same as in other IDEs.

**Comment by php4fan** [comment]
What exactly does formatOnType do? As I said, I have it disabled (never touched it) and yet, I do get auto indentation as I type

**Comment by jakubmisek** [comment]
The `editor.autoIndent` setting is a relatively simple mechanism based on language grammar; putting caret indented after pressing `ENTER`.

The `editor.formatOnType` setting is implemented by the extension - it is triggered when you type `}`, `;`, or  `:`, and performs code formatting of the statement before the trigger character. So usually once you finish typing a statement, it formats it - pretty prints spaces and indents, based on your [codestyle](https://docs.devsense.com/en/vscode/editor/code-styles).

**Comment by php4fan** [comment]
When I type:
```
if (...) {  // and I hit Enter
```
the next line is automatically indented. So I understand that's done by autoIndent.
But then, when I am here:
```
if (....) {
    doThis();
    doThat();
    // <-- caret is there; this line is empty
}
```
and I type a `}`, **the `}` gets automatically un-indented**.

Is this still done by VSCode and not by the extension, and governed by autoIndent? I ask because you only mentioned ENTER.

I DO want basic auto indentation (i.e. getting a decent default indentation which obviously includes auto unindentation), but I'm pretty sure I do NOT want auto formatting (i.e. changing the formatting of what I have already typed, besides basic indentation).

Unindenting a `case` statement is exactly like unindenting a closing `}`, so I think this is something that should be done when one has `autoIndent` regardless of `formatOnType`.

Which means **maybe this belongs in VSCode** and not the extension? After all I think the switch-case statement works pretty much the same in most languages. If decent auto indenting of ifs, loops, function bodies and the like is all already being done by VSCode itself, they should very well be able to manage switch-case statements as well.

**Comment by jakubmisek** [comment]
There is a difference in how it works. Indenting `{` and `}` follows simple language blocks specified in grammar so the basic behavior can be provided by VSCode itself. More complex indent/outdent after pressing `ENTER` is also based on grammar (Defined in [documentation](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#on-enter-rules)) - these indent/outdent rules for PHP language are a part of VSCode [here](https://github.com/microsoft/vscode/blob/ad05897293964be52ad97505124830937d096953/extensions/php/language-configuration.json#L38).

`case` is a bit trickier, it is a multi-character and multi-token construct. Also, it can get mismatched with `case` in `enum` ... So in formatting we have to be aware of various situations, respect multilines, understand the actual syntax, then perform pretty-print, and resolve the indentation (which is configurable, because different users expect different indentation levels for `case` blocks).

So the first one is based on built-in grammar rules, and the second one is a full-blown code format provided by extension.

**Comment by php4fan** [comment]
And can't you do it (the auto-indent part, without auto-formatting anything else) when `formatOnType` is disabled but `autoIndent` is enabled? Whether this is something that VSCode should do or that the extension should do, it should be done.

**Comment by jakubmisek** [comment]
We do it as a part of `formatOnType` because it's quite a difficult implementation)

I'm afraid the `autoIndent`'s outdenting is defined [here](https://github.com/microsoft/vscode/blob/ad05897293964be52ad97505124830937d096953/extensions/php/language-configuration.json#L27) and I'm not sure if we can extend it.

**Comment by jakubmisek** [comment]
Closing the issue

- auto indent of `case` and `switch` works as a part of format-on-type feature (must be enabled)
- smart indent on `enter` is a part of VSCode, we won't be extending that (as noted above).

Thanks!
