### ISSUE TITLE
Function 'implode' has been removed and is available up to PHP 7.4

### ISSUE THREAD

**Issue by menturion** [DEVSENSE/phptools-docs#535]
v1.45.15227 (pre-release)
I am getting a huge number of INFO messages that `Function 'implode' has been removed and is available up to PHP 7.4`, but as you can see here https://www.php.net/manual/de/function.implode.php `implode` was not removed in PHP 8.

**Comment by Morgy93** [comment]
It's probably because of the legacy signature which was misinterpreted here:

<img width="607" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/7961978/760ac7f7-7117-44b0-b490-1a3b1e6c1aab">
<img width="838" alt="image" src="https://github.com/DEVSENSE/phptools-docs/assets/7961978/c5c195d8-5490-4b77-96af-44437614e871">

But yes, the `PHP6405` is wrong here. https://docs.devsense.com/en/vs/code%20validation/diagnostics#compatibility-group

**Comment by jakubmisek** [comment]
Thanks, you are right, the second one is not correct:

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/27ff9cdc-5a2f-4dd0-96f9-1f4b0cdf49b3)

**Comment by jakubmisek** [comment]
thank you - this will be fixed and improved in the upcoming pre-release.

**Comment by menturion** [comment]
Just tested the version v1.45.15249 (pre-release). 
This issue is fixed.

**Comment by jakubmisek** [comment]
Thank you @menturion for the quick update.
