### ISSUE TITLE
Code formatting/highlighting/coloring issues

### ISSUE THREAD

**Issue by eeasoftware** [DEVSENSE/phptools-docs#56]
I've run into a few incorrect code highlighting/coloring issues.  It doesn't show an error, and the code works just fine (Centos 7, php7.4), so I'm pretty sure it's only the color or formatting parser that's an issue.

I tried multiple times to use my account login for devsense.com on the community forum, but either the site just kept timing out or if I could login, just kept going back to the main page regardless of what I clicked on (login, start a discussion, etc), so I posted this here.

1. Multiple Exception types in a catch block separated by a single pipe '|' does not highlight the class name of the first class.
![image1](https://user-images.githubusercontent.com/25559097/78389474-fd692e00-759f-11ea-8241-4a0f388bf71d.png)

2. Namespaced Constant as a default value for a parameter in a function definition is colored incorrectly as well. (image2.png)
![image2](https://user-images.githubusercontent.com/25559097/78389471-fc380100-759f-11ea-8780-e287bd5e5e67.png)

3. When using an Uppercase constant name that is the same as a PHP primitive (in my example: STRING vs string, the coloring is incorrect as a type instead of the constant name. (image3.png)
![image3](https://user-images.githubusercontent.com/25559097/78389473-fcd09780-759f-11ea-9485-8b4f7e823df0.png)

Thank you for a great plugin, I love it a lot!

**Comment by jakubmisek** [comment]
Thank you for the feedback and we're so glad you like our tools! 

---

Sadly the coloring issue is caused by the VSCode's built-in language grammar. We'll take a look if there is anything we can do other than reporting it to https://github.com/microsoft/vscode/issues. For reference there are plenty of other php-highlighting issues already reported:

- https://github.com/microsoft/vscode/issues/87573
- https://github.com/microsoft/vscode/issues/85063
- https://github.com/microsoft/vscode/issues/66715
- https://github.com/microsoft/vscode/issues/88441
- https://github.com/microsoft/vscode/issues/70571
- https://github.com/microsoft/vscode/issues/59545

**Comment by eeasoftware** [comment]
I see, I never thought to look there.  I thought it was all phpTools magic.  Ruins the illusion for me, but I still love the tool.  VSCode didn't highlight my php files until I installed it, so I naturally thought the two were related.

Thank you for reporting it though.  (if you didn't, then let me know so I can, and thank you anyway).

**Comment by jakubmisek** [comment]
phptools add some magic to highlighting, phar files, file formats, in addition to code completion, error checking, debugging etc. :) just colors itself are built in VSCode.

---
If we may ask, please report it with your screenshots, we can upvote and possibly find a workaround.

**Comment by eeasoftware** [comment]
Will do.  Thank you.  I'll reply here with the link once it's posted.

**Comment by jakubmisek** [comment]
Thank you @eeasoftware !

**Comment by eeasoftware** [comment]
I've submitted the report, sorry it took a while.

https://github.com/microsoft/vscode/issues/95559

**Comment by jakubmisek** [comment]
nice! thank you
