### ISSUE TITLE
String operators on undeclared variables

### ISSUE THREAD

**Issue by lhmuk** [DEVSENSE/phptools-docs#571]
![image](https://github.com/DEVSENSE/phptools-docs/assets/83061548/3a536d2a-e0c7-467e-80ca-60c8cd9d6463)

VSCode 1.89.1
PHP Extension 1.47.15561 (pre-release)

The PHP extension does not check for the use of string operators on undeclared variables as an error

**Comment by jakubmisek** [comment]
Thank you for the suggestion. You are right, in the case of `.=` operator, we silenced the warning because there were too many such cases in various legacy PHP frameworks. The regular string concatenation operator `.` gives the warning.

![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/6b5145dd-ca63-43ae-a5ef-2efa8c4e5796)

I think we can stop silencing the warning for the `.=` operator.
