### ISSUE TITLE
Current php version indicator/selector

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#67]
It was already mentioned that this was planned in https://github.com/DEVSENSE/phptools-docs/issues/63#issuecomment-669846601
However It'd be great on my / our side if we had a github issue that we could point at for this specific feature, so also creating this one.

The request from out side was:
> support for language features depending on the PHP version

- [x] language version indicator in status bar, as it is in TypeScript and other languages
- [ ] language selector; upon clicking the version allow to change the version, or change current executable - needed for debugging functionality

**Comment by jakubmisek** [comment]
actually the syntax and problems analysis are sensitive to actual PHP version; 

the version is indicated in "output" window for now:
![image](https://user-images.githubusercontent.com/842150/89534335-06d80080-d7f5-11ea-954b-18c66565949e.png)

and can be changed in your settings `"php.executablePath"` (https://docs.devsense.com/en/vscode/configuration).

But it is a good idea to make an indicator and version selector in VSCode status bar (Python has a similar feature)

**Comment by addshore** [comment]
> But it is a good idea to make an indicator and version selector in VSCode status bar (Python has a similar feature)

Sounds great!

**Comment by micgro42** [comment]
I'm confused. Why does my locally installed PHP version matter at all for the code I write in the editor?
If I have to fix a bug in a piece of software that has to run on PHP 5.3, then it should just be a single configuration that I change in my IDE so that it auto-generates valid language features and highlights if I write something that is not valid for that version. Without me having to find any ancient executable for my OS.

**Comment by jakubmisek** [comment]
@micgro42 I understand; it's just a current limitation of PhpTools, since it affects running tests and running an integrated web server and debugging functionality (for which you need local PHP with Xdebug installed).

We will be adding the version selector in a future update, at least for the case where you are debugging remotely.

**Comment by jakubmisek** [comment]
PHP version indicator added, will be avail. in next update

![image](https://user-images.githubusercontent.com/842150/89712633-6c152880-d992-11ea-96d5-8b137ce4a6c0.png)

**Comment by markkirchner** [comment]
The version selector feature would really be highly appreciated here as well.

Or, maybe as an interims measure: Would it be possible to configure the `php.executablePath` on a per-workspace (or ideally even on a per-workspace-folder) basis? Right now I can only set it system-wide for everything in VS code. This really hurts the ability to work with different projects/components that use diffrent PHP versions.

**Comment by jakubmisek** [comment]
You are right; as for the `php.executablePath` - it is actually provided by vscode itself, so we can't change its scope (machine vs. workspace vs. folder). Since it contains a local path to the binary file, it only makes sense to have it defined per-machine.

I would suggest a setting like `"php.version": "8.0"` that would allow setting the desired minimal PHP version for your workspace; Its default value would be inherited from `composer.json` if there is any.

Available PHP versions can be determined automatically tho.

**Comment by markkirchner** [comment]
Oh well, too bad about `php.executablePath` then. I had hoped that this might be an easier way of getting at least a partial solution. Thanks for the explanation.

So yeah, something like a `php.version` setting would really be great. Is there any kind of timeline / release plan / ... to which requests like this are added? In order to get at least a rough idea when to expect it?

**Comment by jakubmisek** [comment]
the `php.version` would be ours and it could be changed from the status bar indicator above. We have it in the todo for the next update with a month :)

**Comment by jakubmisek** [comment]
The upcoming update provides the option to choose PHP version within a workspace. (https://docs.devsense.com/en/vscode/editor/php-version-select)

Thank you for all the feedback!
