### ISSUE TITLE
VSC Refactoring

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#7]
Allways get this message when try to refactor:

[Error - 8:34:55 PM] Request textDocument/rename failed.
  Message: Refactoring cannot be completed. Some changes might corrupt your code.
  Code: 102

**Comment by jakubmisek** [comment]
You are right, this happens in some cases where we cannot safely change the code. For example when there is a file in your workspace with a syntax error.

We'll improve this feature and also add more details into the error message.

For local variables I guess it should work always ?

**Comment by Mordef** [comment]
Made 2 small test:
Single file, no class/namespace: all fine
Workspace Class with namesapse, protected property with getter/setter
try to change protected property fails with code 102

![grafik](https://user-images.githubusercontent.com/22061464/48505447-60411480-e847-11e8-9b78-ef894c43bf22.png)

No warnings/errors in workspace

**Comment by jakubmisek** [comment]
thanks, will try and hopefully fix this issue

**Comment by jakubmisek** [comment]
as of `1.0` version, phptools are only allowing rename of a local/global variable, function name or a class/interface/trait name. We might enable it for properties and methods, maybe just private and protected, because the dynamic nature of the PHP language might cause you some troubles when you are doing things like `$x->$propname` or `function_exists($fooname)` ...

**Comment by jakubmisek** [comment]
- updated informational messages
- rename of class members will be added in a future update (possible for private members first)
